FROM debian:12

WORKDIR /testing

COPY . .

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    wget \
    curl \
    unzip \
    pkg-config \
    libssl-dev \
    python3 \
    python3-pip

RUN mkdir -p /testing/Autotests/build

WORKDIR /testing/Autotests/build

RUN cmake .. && make -j$(nproc)
CMD ["./tests"]
