name: trading_bot_ci

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  stock_market_availability:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set permissions for availability script
        run: chmod +x ./Scripts/availability_check.sh
      - name: Check stock market availability
        run: ./Scripts/availability_check.sh

  setup-docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Docker
        run: |
          sudo apt-get update && sudo apt-get install -y ca-certificates curl gnupg lsb-release
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc > /dev/null
          sudo chmod a+r /etc/apt/keyrings/docker.asc
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
          https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      - name: Start Docker service
        run: sudo systemctl start docker
      - name: Verify Docker installation
        run: docker --version

  autotests:
    runs-on: ubuntu-22.04
    needs: [stock_market_availability, setup-docker]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run autotest
        run: |
          sudo docker build -f Dockerfile.test -t testing .
          sudo docker run --rm testing

  backtests:
    runs-on: ubuntu-22.04
    needs: [stock_market_availability, setup-docker]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run backtesting
        run: |
          sudo docker build -f Dockerfile.backtesting -t backtesting .
          sudo docker run --rm -v ${{ github.workspace }}/Backtesting/data:/backtesting/Backtesting/data backtesting
      - name: Upload Backtesting Results
        uses: actions/upload-artifact@v4
        with:
          name: backtesting-results
          path: Backtesting/data/backtesting_results/
          retention-days: 7
