name: trading_bot_ci

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  stock_market_availability:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set permissions for availability script
        run: chmod +x ./Scripts/availability_check.sh

      - name: Check stock market availability
        run: ./Scripts/availability_check.sh

  autotests:
    runs-on: ubuntu-22.04
    needs: stock_market_availability
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates curl gnupg lsb-release \
            docker-ce docker-ce-cli containerd.io

      - name: Start Docker service
        run: sudo systemctl start docker

      - name: Verify Docker installation
        run: docker --version

      - name: Run autotest
        run: |
          docker build -f Dockerfile.test -t testing .
          docker run --rm testing

  backtests:
    runs-on: ubuntu-22.04
    needs: stock_market_availability
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates curl gnupg lsb-release \
            docker-ce docker-ce-cli containerd.io

      - name: Start Docker service
        run: sudo systemctl start docker

      - name: Verify Docker installation
        run: docker --version

      - name: Ensure data directory exists on host
        run: mkdir -p ${{ github.workspace }}/Backtesting/data/backtesting_results

      - name: Debug before backtesting
        run: ls -la ${{ github.workspace }}/Backtesting/data

      - name: Run backtesting in Docker
        run: |
          docker build -f Dockerfile.backtesting -t backtesting_image .
          CONTAINER_ID=$(docker run -d -v ${{ github.workspace }}/Backtesting/data:/backtesting/Backtesting/data backtesting_image)
          
          docker wait $CONTAINER_ID

          docker exec $CONTAINER_ID ls -la /backtesting/Backtesting/data/backtesting_results

          docker cp $CONTAINER_ID:/backtesting/Backtesting/data/backtesting_results ${{ github.workspace }}/Backtesting/data/

          docker rm $CONTAINER_ID

      - name: Debug after backtesting
        run: ls -la ${{ github.workspace }}/Backtesting/data/backtesting_results

      - name: Ensure files exist
        run: |
          if [ -z "$(ls -A ${{ github.workspace }}/Backtesting/data/backtesting_results)" ]; then
            echo "Error: No backtesting results found!"
            exit 1
          fi

      - name: Upload backtesting results
        uses: actions/upload-artifact@v4
        with:
          name: backtesting-results
          path: ${{ github.workspace }}/Backtesting/data/backtesting_results/
          if-no-files-found: error
