name: trading_bot_ci

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  stock_market_availability:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  #

      - name: Set permissions for availability script
        run: chmod +x ./Scripts/availability_check.sh

      - name: Check stock market availability
        run: ./Scripts/availability_check.sh

  autotests:
    runs-on: ubuntu-22.04
    needs: stock_market_availability
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Обновлено с v3 на v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates curl gnupg lsb-release \
            docker-ce docker-ce-cli containerd.io

      - name: Start Docker service
        run: sudo systemctl start docker

      - name: Verify Docker installation
        run: docker --version

      - name: Run autotest
        run: |
          docker build -f Dockerfile.test -t testing .
          docker run --rm testing

  backtests:
    runs-on: ubuntu-22.04
    needs: stock_market_availability
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Обновлено с v3 на v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates curl gnupg lsb-release \
            docker-ce docker-ce-cli containerd.io

      - name: Start Docker service
        run: sudo systemctl start docker

      - name: Verify Docker installation
        run: docker --version

      - name: Run backtesting
        run: |
          docker build -f Dockerfile.backtesting -t backtesting_image .
          docker run --rm -v ${{ github.workspace }}/Backtesting/data/backtesting_results:/Backtesting/data/backtesting_results backtesting_image

      - name: Upload backtesting results
        uses: actions/upload-artifact@v4
        with:
          name: backtesting-results
          path: Backtesting/data/backtesting_results/
