name: trading_bot_ci.yml

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  stock_market_availability:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check stock market availability
        run: ./Scripts/availability_check.sh

  backtesting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Extract data for backtesting
        run: |
          set -e
          cd Backtesting/src
          for year in {2020..2024}
          do
            if [ ! -f "data/Data_extracted/5m/BTCUSDT/${year}.csv" ]; then
              python3 binance_stats.py BTCUSDT 5m $year >> data_extraction.log 2>&1
              echo "Data for year $year extracted."
            else
              echo "Data for year $year already exists. Skipping."
            fi
          done
          echo "Data extraction completed."

      - name: Build and run backtesting
        run: |
          set -e
          cd Backtesting
          rm -rf build && mkdir build && cd build
          cmake ../
          make -j`nproc` || { echo "Build failed"; exit 1; }
          ./backtesting >> backtesting_results.log 2>&1
          echo "Backtesting completed."

      - name: Notify completion
        run: echo "Backtesting workflow completed successfully."

  autotest:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Build autotests
        run: |
          cd Autotests && mkdir -p build && cd build
          cmake ../
          make -j`nproc`

      - name: Run autotests
        run: |
          ./test_ || { echo "Tests failed"; exit 1; }

      - name: Notify completion
        run: echo "Autotest workflow completed successfully."
